### ISSUE TITLE
On your team's page, the linked text "and much, much more." goes to an invalid link 

### ISSUE THREAD

**Issue by Goldenlion5648** [rakugoteam/rakugoteam.github.io#21]
title: "Your github team page"
excerpt:  the linked text "and much, much more." goes to an invalid link 
url: "https://github.com/rakugoteam"

**Comment by Jeremi360** [comment]
@Goldenlion5648 thanks for pointing that out this should lead to: <https://rakugoteam.github.io/features/> , I will fix this asap.

**Comment by Jeremi360** [comment]
Fixed :D @Goldenlion5648
